/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.*;
import static View.MainWindow.conn;
import Controller.DataRenderer;
import Controller.DataRenderer;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author skasa
 */
public class DeleteProduct extends javax.swing.JFrame {

    Statement st;
    ResultSet rs;
    private String tblCode;
    DataRenderer fetched = new DataRenderer(conn);
    
    public DeleteProduct(String tblCode) {
        initComponents();
        this.tblCode = tblCode;
        setResizable(false);
        setUndecorated(false);
        
        try {
            st = conn.prepareStatement("SELECT * FROM tblproductcategory");
            rs = st.executeQuery("SELECT * FROM tblproductcategory");
            while (rs.next()) {
                String item;
                item = rs.getString("category_name");
                categoryCB.addItem(item);
                
            }
            st = conn.prepareStatement("SELECT * FROM tblproductunit");
            rs = st.executeQuery("SELECT * FROM tblproductunit");
            while (rs.next()) {
                String unit;
                unit = rs.getString("unit_name");
                unitCB.addItem(unit);
                
            }
            setVisibleData();
        } catch (SQLException ex) {
            Logger.getLogger(AddProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        deleteBtn.setBackground(Color.red);
        cancelBtn.setBackground(Color.DARK_GRAY);
    }
    
    void setVisibleData() throws SQLException {
        st = conn.prepareStatement("SELECT * FROM tblproduct WHERE produce_code='"+tblCode+"'");
        rs = st.executeQuery("SELECT * FROM tblproduct WHERE produce_code='"+tblCode+"'");
        rs.next();
        itemNameLbl.setText(rs.getString("product_name"));
        codeTf.setText(tblCode);
        codeTf.setEditable(false);
        codeTf.setEnabled(false);
        nameTf.setText(rs.getString(4));
        nameTf.setEditable(false);
        nameTf.setEnabled(false);
        unitCB.setSelectedIndex(rs.getInt("unit_id"));
        unitCB.setEditable(false);
        unitCB.setEnabled(false);
        categoryCB.setSelectedIndex(rs.getInt("category_id"));
        categoryCB.setEditable(false);
        categoryCB.setEnabled(false);
        unitTf.setText(String.valueOf(rs.getFloat("unit_in_stock")));
        unitTf.setEditable(false);
        unitTf.setEnabled(false);
        discountTf.setText(String.valueOf(rs.getFloat("discount_percentage")));
        discountTf.setEditable(false);
        discountTf.setEnabled(false);
        reOderTf.setText(String.valueOf(rs.getFloat("reorder_level")));
        reOderTf.setEditable(false);
        reOderTf.setEnabled(false);
        List usr = fetched.fetchUser(rs.getInt("user_id"));
        userNameLbl.setText((String) usr.get(0));
        desiLbl.setText((String) usr.get(1));
        dateLbl.setText(rs.getString("added_date"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        categoryCB = new javax.swing.JComboBox<>();
        designationLbl = new javax.swing.JLabel();
        desiLbl = new javax.swing.JLabel();
        unitCB = new javax.swing.JComboBox<>();
        dateLbl = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        userNameLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        reOderTf = new javax.swing.JTextField();
        discountTf = new javax.swing.JTextField();
        unitTf = new javax.swing.JTextField();
        nameTf = new javax.swing.JTextField();
        codeTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        itemNameLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setName("UpdateProductFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("DELETE");
        jPanel1.add(deleteBtn);
        deleteBtn.setBounds(490, 690, 130, 35);

        categoryCB.setBackground(new java.awt.Color(255, 255, 204));
        categoryCB.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        categoryCB.setForeground(new java.awt.Color(51, 51, 51));
        categoryCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jPanel1.add(categoryCB);
        categoryCB.setBounds(251, 258, 369, 35);

        designationLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        designationLbl.setForeground(new java.awt.Color(51, 51, 51));
        designationLbl.setText("DESIGNATION:");
        designationLbl.setFocusable(false);
        jPanel1.add(designationLbl);
        designationLbl.setBounds(39, 546, 146, 27);

        desiLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        desiLbl.setForeground(new java.awt.Color(51, 51, 51));
        desiLbl.setFocusable(false);
        jPanel1.add(desiLbl);
        desiLbl.setBounds(251, 546, 316, 32);

        unitCB.setBackground(new java.awt.Color(255, 255, 204));
        unitCB.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        unitCB.setForeground(new java.awt.Color(51, 51, 51));
        unitCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jPanel1.add(unitCB);
        unitCB.setBounds(251, 205, 369, 35);

        dateLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(51, 51, 51));
        dateLbl.setFocusable(false);
        jPanel1.add(dateLbl);
        dateLbl.setBounds(251, 591, 335, 27);

        cancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn);
        cancelBtn.setBounds(39, 696, 129, 35);

        userNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        userNameLbl.setForeground(new java.awt.Color(51, 51, 51));
        userNameLbl.setFocusable(false);
        jPanel1.add(userNameLbl);
        userNameLbl.setBounds(251, 495, 327, 33);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("ADDED DATE:");
        jLabel10.setFocusable(false);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(39, 591, 122, 27);

        reOderTf.setBackground(new java.awt.Color(255, 255, 204));
        reOderTf.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        reOderTf.setForeground(new java.awt.Color(0, 0, 0));
        reOderTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reOderTfActionPerformed(evt);
            }
        });
        jPanel1.add(reOderTf);
        reOderTf.setBounds(251, 417, 369, 35);

        discountTf.setBackground(new java.awt.Color(255, 255, 204));
        discountTf.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        discountTf.setForeground(new java.awt.Color(0, 0, 0));
        discountTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTfActionPerformed(evt);
            }
        });
        jPanel1.add(discountTf);
        discountTf.setBounds(251, 364, 369, 35);

        unitTf.setBackground(new java.awt.Color(255, 255, 204));
        unitTf.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        unitTf.setForeground(new java.awt.Color(0, 0, 0));
        unitTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitTfActionPerformed(evt);
            }
        });
        jPanel1.add(unitTf);
        unitTf.setBounds(251, 311, 369, 35);

        nameTf.setBackground(new java.awt.Color(255, 255, 204));
        nameTf.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        nameTf.setForeground(new java.awt.Color(0, 0, 0));
        nameTf.setMaximumSize(null);
        nameTf.setPreferredSize(null);
        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });
        jPanel1.add(nameTf);
        nameTf.setBounds(251, 152, 369, 35);

        codeTf.setBackground(new java.awt.Color(255, 255, 204));
        codeTf.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        codeTf.setForeground(new java.awt.Color(0, 0, 0));
        codeTf.setNextFocusableComponent(nameTf);
        codeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeTfActionPerformed(evt);
            }
        });
        jPanel1.add(codeTf);
        codeTf.setBounds(251, 99, 369, 35);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("ADDED BY:");
        jLabel9.setFocusable(false);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(39, 501, 122, 27);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("REORDER LEVEL:");
        jLabel8.setFocusable(false);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(39, 421, 161, 27);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("DISCOUNT:");
        jLabel7.setFocusable(false);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(39, 368, 122, 27);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("NUMBER OF UNITS:");
        jLabel6.setFocusable(false);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(39, 315, 174, 27);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("CATEGORY:");
        jLabel5.setFocusable(false);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(39, 266, 122, 27);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("UNIT TYPE:");
        jLabel4.setFocusable(false);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(39, 209, 122, 27);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("ITEM NAME:");
        jLabel3.setFocusable(false);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(39, 156, 122, 27);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ITEM CODE:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(39, 103, 122, 27);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("Delete");
        jLabel1.setFocusable(false);
        jPanel2.add(jLabel1);

        itemNameLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        itemNameLbl.setForeground(new java.awt.Color(204, 51, 0));
        itemNameLbl.setFocusable(false);
        jPanel2.add(itemNameLbl);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 51, 0));
        jLabel11.setText("?");
        jPanel2.add(jLabel11);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 20, 510, 40);

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(685, 816));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeTfActionPerformed

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void unitTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitTfActionPerformed

    private void discountTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountTfActionPerformed

    private void reOderTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reOderTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reOderTfActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        try {
            //</editor-fold>
            //</editor-fold>
            conn = Model.ConnectDB.connect();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeleteProduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DeleteProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> categoryCB;
    private javax.swing.JTextField codeTf;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel desiLbl;
    private javax.swing.JLabel designationLbl;
    private javax.swing.JTextField discountTf;
    private javax.swing.JLabel itemNameLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameTf;
    private javax.swing.JTextField reOderTf;
    private javax.swing.JComboBox<String> unitCB;
    private javax.swing.JTextField unitTf;
    private javax.swing.JLabel userNameLbl;
    // End of variables declaration//GEN-END:variables
}
